language: android
jdk: oraclejdk8

notifications:      
  email: false 

android:
  components:
    - tools
    - build-tools-24.0.1
    - android-24
    - extra-android-m2repository
    - extra-android-support

  licenses:
    - 'android-sdk-license.*'


# Emulator Management: Create, Start and Wait
before_script:
  - chmod +x gradlew

  - echo no | android create avd --force -n mobiletest -t android-19 --abi armeabi-v7a
  - emulator -avd mobiletest -no-skin -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &

script:
  - ./gradlew build  

before_cache:
  - cat /home/travis/build/karonl/testTravis/InDoorView/build/reports/androidTests/connected/index.html
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/